
[book]
title = "Towards becoming a Rustacean"
authors = ["Aheebwa Michael"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/AheebwaMike/hello-rust"
edit-url-template = "https://github.com/AheebwaMike/hello-rust/edit/main/docs/src/{path}"